export interface FrameworkStep {
  n: string; // Step name (e.g. Problem, Agitate)
  d: string; // Detailed description of the step
  ex: string; // Concrete example for client-facing inspiration
}

export interface ContentFramework {
  id: number;
  name: string;
  funnel: 'tof' | 'mof' | 'bof';
  desc: string;
  tags: string[];
  steps: FrameworkStep[];
}

export interface HookType {
  id: string;
  label: string;
  name: string;
  formula: string;
  ex: string;
  strength: number;
}

export interface HashtagItem {
  tag: string;
  vol: string;
  added: boolean;
}

export interface HashtagsDataset {
  [category: string]: HashtagItem[];
}

export const FW: ContentFramework[] = [
  {id:1,name:"Before - After - Bridge",funnel:"tof",desc:"Sadarkan posisi audience, visualisasikan kondisi ideal, tawarkan jembatan solusi.",tags:["Awareness","Viral","Storytelling"],steps:[{n:"Before",d:"Gambarkan kondisi audience saat ini yang menyakitkan — satu kalimat spesifik.",ex:"Wajah jadi jerawatan karena salah pilih skin care."},{n:"After",d:"Visualisasikan kondisi ideal yang mereka inginkan — harus spesifik dan emosional.",ex:"Bayangkan kamu tahu treatment yang udah pasti berhasil."},{n:"Bridge",d:"Tawarkan produk/konten sebagai jembatan untuk sampai ke kondisi After.",ex:"Jangan coba-coba lagi, lakukan treatment wajah ini."}]},
  {id:2,name:"Problem - Agitate - Solve",funnel:"tof",desc:"Bangun ketakutan dari masalah, perdalam keresahan, hadir sebagai solusi.",tags:["Viral","Fear","Hook"],steps:[{n:"Problem",d:"Sebut masalah spesifik yang dirasakan audience — langsung ke inti.",ex:"Rambut rontok jangan pernah dibiarkan."},{n:"Agitate",d:"Perdalam dengan konsekuensi yang lebih besar jika tidak diselesaikan.",ex:"Karena kebotakan berawal dari rambut yang terus rontok."},{n:"Solve",d:"Hadirkan solusi dengan percaya diri.",ex:"Gunakan produk ini untuk menghalau kebotakan."}]},
  {id:3,name:"AIDA (Attention, Interest, Desire, Action)",funnel:"tof",desc:"Formula klasik AIDA yang terbukti menggerakkan audiens dari kepo hingga beli.",tags:["Classic","Awareness","CTA"],steps:[{n:"Attention",d:"Ciptakan perhatian instan — adegan, pertanyaan mengejutkan, atau fakta aneh.",ex:"Akhirnya saya bisa berbicara dengan kucing saya."},{n:"Interest",d:"Bangun konteks yang membuat mereka penasaran.",ex:"Dan semalam kucing saya bilang mau minta ganti makanan."},{n:"Desire",d:"Tunjukkan manfaat unik yang membuat mereka menginginkan solusi kamu.",ex:"Kamu bisa lakukan ini biar anabul kamu tambah happy."},{n:"Action",d:"Satu CTA yang jelas — tidak boleh lebih dari satu.",ex:"Dapatkan alatnya sekarang dengan klik link ini."}]},
  {id:4,name:"Psychological Open Loop",funnel:"tof",desc:"Ciptakan ketakutan mendalam yang terus-menerus dipikirkan audience.",tags:["Psychology","Viral","Retention"],steps:[{n:"Fear Hook",d:"Temukan satu fear terbesar audience — harus sangat spesifik dan relevan.",ex:"Kehilangan 10 followers sama dengan kehilangan 10 pembelian."},{n:"Amplifikasi",d:"Hitung dampak nyata dengan angka atau konsekuensi konkret.",ex:"Apalagi kalau harga produk kamu bernilai jutaan."},{n:"Loop Terbuka",d:"Jangan langsung beri solusi — biarkan mereka mencari tahu lebih.",ex:"Ada 1 cara mudah untuk menghentikan ini..."}]},
  {id:5,name:"Unexpected - Problem",funnel:"tof",desc:"Lawan kebiasaan umum audience dengan perspektif berlawanan yang mengejutkan.",tags:["Controversial","Viral","Disruptive"],steps:[{n:"Unexpected",d:"Nyatakan hal yang sering dilakukan audience itu salah.",ex:"Percuma konsisten posting tiap hari."},{n:"Problem",d:"Jelaskan konsekuensi nyata dari kebiasaan itu.",ex:"Kalau ga ada strategy ini, pertumbuhan views tetap lambat."},{n:"POV Kamu",d:"Berikan perspektif baru — yang mengarah ke solusi kamu.",ex:"Karena yang terpenting adalah value content-nya."}]},
  {id:6,name:"Myth or Fact?",funnel:"tof",desc:"Ajak audience membuktikan kebenaran — engagement dan rasa penasaran tinggi.",tags:["Engagement","Viral","Interactive"],steps:[{n:"Myth Label",d:"Buka dengan 'Mitos atau Fakta?' untuk memancing rasa ingin tahu.",ex:"Mitos atau fakta?"},{n:"Klaim",d:"Sampaikan klaim yang banyak dipercaya tapi perlu dibuktikan.",ex:"Minimal posting 3 content untuk bisa FYP?"},{n:"Bukti",d:"Buktikan dengan data, pengalaman, atau demonstrasi nyata.",ex:"Kita buktikan disini dengan metode ini."}]},
  {id:7,name:"TRAP Formula",funnel:"tof",desc:"Gunakan kondisi 'jebakan' yang tidak disukai siapapun untuk menarik perhatian.",tags:["Psychology","Hook","Viral"],steps:[{n:"Jebakan",d:"Gambarkan situasi dimana banyak orang terjebak — harus relatable.",ex:"Kebanyakan orang tua terjebak dalam mengembangkan sensorik anak."},{n:"Penyebab",d:"Ungkap penyebab jebakan yang tidak disadari sebelumnya.",ex:"Karena menyepelekan beberapa poin ini."},{n:"Jalan Keluar",d:"Kamu adalah kunci keluar dari jebakan.",ex:"Ini cara memastikan anak kamu bebas dari jebakan ini."}]},
  {id:8,name:"Attention - Story - Solution",funnel:"tof",desc:"Bangun cerita menarik sebagai jembatan menuju solusi.",tags:["Storytelling","Engagement","Viral"],steps:[{n:"Attention",d:"Buka dengan sesuatu yang langsung mencuri perhatian.",ex:"Jadi director marketing padahal hanya lulusan D3."},{n:"Story",d:"Ceritakan proses atau kisah yang relevan.",ex:"Cerita kesialan gue lari pagi ketemu temen baru di pinggir jalan."},{n:"Solution",d:"Hubungkan kisah dengan solusi.",ex:"Cerita ini bakal menjawab pertanyaan lo yang masih bingung."}]},
  {id:9,name:"Failed - Growth - Success",funnel:"tof",desc:"Storytelling transformasi dari gagal, bangkit, hingga berhasil.",tags:["Storytelling","Inspire","Relatable"],steps:[{n:"Failed",d:"Ceritakan kegagalan secara spesifik — semakin detail semakin relatable.",ex:"Udah bikin 30 content, tapi hasilnya nihil."},{n:"Growth",d:"Ungkap momen turning point dan apa yang berubah.",ex:"Sampai akhirnya semangat lagi karena tahu strategi ini."},{n:"Success",d:"Tunjukkan hasil nyata yang kamu capai.",ex:"Yang akhirnya bikin 3 content saya terakhir bisa viral."}]},
  {id:10,name:"Success - Failed - Insight",funnel:"tof",desc:"Plot twist: dari pencapaian, tiba-tiba gagal, lalu insight berharga.",tags:["Storytelling","Hook","Surprising"],steps:[{n:"Success",d:"Mulai dengan pencapaian yang membuat audience impressed.",ex:"Kaget tiba-tiba penjualan meningkat 200%."},{n:"Failed",d:"Ceritakan kejatuhan tak terduga setelah pencapaian.",ex:"Tapi ga lama kemudian malah berbalik minus."},{n:"Insight",d:"Bagikan pelajaran berharga.",ex:"Kamu harus hindari pengalaman saya ini."}]},
  {id:11,name:"Simple & Fast",funnel:"tof",desc:"Sampaikan solusi yang terkesan mudah dan cepat — memanfaatkan keinginan instan.",tags:["Easy","Quick","Accessible"],steps:[{n:"Label Simple",d:"Gunakan 'simple & cepat' di bagian paling awal sebagai hook.",ex:"Cara simple & cepat"},{n:"Masalah",d:"Sebutkan masalah yang ingin diselesaikan.",ex:"untuk mengatur keuangan"},{n:"Benefit",d:"Langsung ke manfaat tanpa basa-basi.",ex:"agar bisa menabung lebih banyak setiap bulan."}]},
  {id:12,name:"HACKS Formula",funnel:"tof",desc:"Manfaatkan kecintaan orang pada cara instan dengan kata 'HACKS'.",tags:["Viral","Instant","Catchy"],steps:[{n:"Topik HACKS",d:"Gabungkan topik dengan kata HACKS.",ex:"Negosiasi HACKS untuk salesman"},{n:"Target",d:"Spesifikkan siapa yang akan mendapat manfaat.",ex:"buat kamu yang sering ketemu calon customer susah"},{n:"Hasil",d:"Sebutkan outcome yang diharapkan.",ex:"agar calon customer beli tanpa mikir."}]},
  {id:13,name:"Never - Number",funnel:"tof",desc:"Larangan dipadukan dengan angka menciptakan hook yang kuat.",tags:["Hook","Number","Restrictive"],steps:[{n:"Larangan",d:"Gunakan 'Jangan pernah...' untuk menciptakan urgensi.",ex:"Jangan pernah belajar berkendara mobil"},{n:"Kondisi",d:"Tambahkan syarat atau angka yang membuat audience penasaran.",ex:"sebelum kamu memiliki 3 hal ini"},{n:"Hint",d:"Beri clue tentang apa yang akan mereka pelajari.",ex:"karena ini yang menentukan keamanan kamu di jalan."}]},
  {id:14,name:"Tips Jitu - For",funnel:"tof",desc:"Formula tips yang menarget segmen spesifik dengan kata kunci 'JITU'.",tags:["Tips","Targeted","Actionable"],steps:[{n:"Tips Jitu",d:"Buka dengan 'Tips JITU' sebagai hook.",ex:"Tips JITU menguasai bahasa Inggris"},{n:"Target",d:"Tentukan target audiens sangat spesifik.",ex:"untuk kamu yang ingin lulus ujian TOEFL dalam 30 hari"}]},
  {id:15,name:"Secret - How",funnel:"tof",desc:"Kemas informasi seolah eksklusif — menciptakan rasa beruntung.",tags:["Exclusive","Psychology","FOMO"],steps:[{n:"Bocoran",d:"Gunakan kata 'bocoran', 'spesial', atau 'rahasia'.",ex:"Saya bocorkan tips artis dalam merawat kesehatan kulitnya"},{n:"Detail",d:"Jelaskan detail yang membuat audience merasa mendapat info privileged.",ex:"hanya menggunakan 2 produk ini yang jarang diketahui orang."}]},
  {id:16,name:"Features - Advantages - Benefits",funnel:"mof",desc:"Tonjolkan fitur, keunggulan, hingga manfaat nyata yang dirasakan audience.",tags:["Product","Education","Trust"],steps:[{n:"Features",d:"Sebutkan fitur utama secara konkret dan spesifik.",ex:"Tools lengkap untuk social media analytics."},{n:"Advantages",d:"Jelaskan apa yang membuat fitur ini lebih unggul.",ex:"Membantu kamu menemukan topik yang sedang trend."},{n:"Benefits",d:"Terjemahkan ke manfaat nyata yang dirasakan langsung.",ex:"Sehingga bisa mendapatkan content yang viral setiap posting."}]},
  {id:17,name:"Problem - Promise - Prove",funnel:"mof",desc:"Highlight masalah, beri janji, lalu buktikan dengan bukti nyata.",tags:["Trust","Proof","Credibility"],steps:[{n:"Problem",d:"Identifikasi masalah spesifik target audience.",ex:"Budget kamu boncos karena ads yang jelek?"},{n:"Promise",d:"Berikan janji atau ekspektasi yang jelas.",ex:"Jangan pusing, karena content organik juga bisa menciptakan penjualan."},{n:"Prove",d:"Tunjukkan bukti nyata — screenshot, data, testimoni.",ex:"Ini hasil penjualan saya bulanan ini tanpa menggunakan ads."}]},
  {id:18,name:"Star - Story - Solution",funnel:"mof",desc:"Bangun kepercayaan melalui cerita karakter yang inspiratif.",tags:["Storytelling","Trust","Case Study"],steps:[{n:"Star",d:"Perkenalkan karakter utama yang relatable.",ex:"Dani, sales mobil yang berhasil menjual 100 unit dari telemarketing."},{n:"Story",d:"Ceritakan proses perjuangan karakter.",ex:"Padahal awalnya sempat mau resign karena merasa tidak cocok."},{n:"Solution",d:"Ungkap solusi yang mengubah segalanya.",ex:"Semua berubah ketika Dani mempelajari tips telemarketing ini."}]},
  {id:19,name:"Best Benefit - Who",funnel:"mof",desc:"Tawarkan benefit maksimal dan targetkan secara spesifik.",tags:["Targeted","Value","Segmentation"],steps:[{n:"Best Benefit",d:"Berikan benefit yang terasa berlebih — gunakan kata 'lengkap', 'full', 'complete'.",ex:"Framework content LENGKAP step by step"},{n:"Who",d:"Tentukan secara spesifik untuk siapa.",ex:"untuk creator pemula yang ingin viral dalam 30 hari."}]},
  {id:20,name:"Problem - Number - Solution (Masalah)",funnel:"mof",desc:"Highlight lebih dari 1 masalah menggunakan angka.",tags:["Education","List","Issues"],steps:[{n:"Problem",d:"Sebutkan tema besar masalah.",ex:"Stress karena merasa tidak pernah bisa konsisten posting."},{n:"Number",d:"Gunakan angka untuk membuat konten terstruktur.",ex:"Ini 3 penyebab utamanya"},{n:"Solution",d:"Tawarkan solusi yang menyelesaikan semua masalah.",ex:"Hindari hal ini agar bisa konsisten secepat mungkin."}]},
  {id:21,name:"Problem - Number - Solution (Solusi)",funnel:"mof",desc:"Angka digunakan untuk highlight jumlah solusi.",tags:["Education","List","Solutions"],steps:[{n:"Problem",d:"Sampaikan masalah secara emosional.",ex:"Jangan nyesel karena udah beli kacamata yang salah."},{n:"Number Solusi",d:"Gunakan angka untuk jumlah solusi kamu.",ex:"Kamu bisa gunakan 4 step ini"},{n:"Outcome",d:"Jelaskan apa yang dicapai setelah mengikuti solusi.",ex:"agar bisa memastikan kacamata yang kamu pilih pasti fit."}]},
  {id:22,name:"The 3 Reason Why",funnel:"mof",desc:"Bangun kepercayaan dengan 3 alasan kuat mengapa harus memilih kamu.",tags:["Trust","Credibility","Social Proof"],steps:[{n:"Why #1",d:"Alasan pertama — paling kuat dan mudah diverifikasi.",ex:"Serum terbaik bulan ini berdasarkan review 10.000 pengguna."},{n:"Why #2",d:"Bukti sosial atau angka yang memperkuat kepercayaan.",ex:"Terjual lebih dari 1000 pcs hanya dalam 1 minggu."},{n:"Why #3",d:"Tutup dengan garansi atau bukti hasil nyata.",ex:"99% berhasil mendapatkan khasiat di wajah mereka."}]},
  {id:23,name:"Solution - Time",funnel:"mof",desc:"Perkuat benefit dengan dimensi waktu yang membuat audience terkesan.",tags:["Urgency","Timeframe","Quick Win"],steps:[{n:"Solution",d:"Sebutkan solusi yang ditawarkan secara langsung.",ex:"Cara bisa menguasai public speaking"},{n:"Time",d:"Tambahkan jangka waktu spesifik yang membuat audience terkesan.",ex:"hanya dalam waktu 1 minggu — tanpa perlu kursus mahal."}]},
  {id:24,name:"What - Who (Tutorial)",funnel:"mof",desc:"Tutorial langsung dengan target spesifik.",tags:["Tutorial","Targeted","Education"],steps:[{n:"What",d:"Jelaskan apa yang akan diajarkan.",ex:"Tutorial dapetin tubuh ideal"},{n:"Who/Method",d:"Spesifikkan metode atau sumber yang digunakan.",ex:"dari 5 gerakan yang sudah dijelaskan di e-book ini."}]},
  {id:25,name:"Niche - Problem - Solution",funnel:"mof",desc:"Targetkan niche sangat spesifik untuk mendapatkan audiens berkualitas.",tags:["Niche","Quality","Targeted"],steps:[{n:"Niche",d:"Sebut langsung kelompok spesifik yang menjadi target.",ex:"Gitaris pemula wajib ketahui hal ini."},{n:"Problem Niche",d:"Sebutkan masalah spesifik yang hanya dihadapi niche tersebut.",ex:"3 penyebab sound gitar kamu ga enak didengar"},{n:"Solution",d:"Berikan solusi yang terasa dibuat khusus untuk mereka.",ex:"Dan gimana cara menghindarinya dengan teknik mixing yang benar."}]},
  {id:26,name:"How - Just",funnel:"mof",desc:"Tunjukkan cara sederhana dengan tools atau resource minimal.",tags:["Simplicity","Accessible","Education"],steps:[{n:"How",d:"Buka dengan 'cara' untuk melakukan sesuatu yang terkesan kompleks.",ex:"Cara learning good content dari akun sejenis"},{n:"Just",d:"Tambahkan 'hanya' yang membuat solusi terkesan mudah.",ex:"hanya dari free tools yang sudah ada di smartphone kamu."}]},
  {id:27,name:"One Stop Solution",funnel:"mof",desc:"Tunjukkan bagaimana satu solusi bisa digunakan untuk banyak kebutuhan.",tags:["Value","Versatile","Education"],steps:[{n:"Satu Solusi",d:"Perkenalkan satu produk atau metode yang menjadi fokus.",ex:"Kecanggihan teknologi di sneakers terbaru ini"},{n:"Banyak Kegunaan",d:"Daftarkan berbagai use case dari satu solusi tersebut.",ex:"bisa digunakan untuk fashion, running, bahkan riding."}]},
  {id:28,name:"Extreme - One Stop Solution",funnel:"mof",desc:"Satu solusi untuk SANGAT banyak hal — wow factor tinggi.",tags:["Value","WOW","Versatile"],steps:[{n:"Satu Solusi Ekstrem",d:"Perkenalkan solusi yang bisa memenuhi kebutuhan dalam jumlah mengejutkan.",ex:"1 Template design"},{n:"Kegunaan Ekstrem",d:"Sebutkan angka mengejutkan tentang berapa banyak hal yang bisa diselesaikan.",ex:"yang bisa kamu gunakan untuk lebih dari 100 content berbeda."}]},
  {id:29,name:"Credibility - Solution",funnel:"mof",desc:"Manfaatkan kredibilitas pihak lain untuk memperkuat posisi produk kamu.",tags:["Authority","Trust","Borrowed Credibility"],steps:[{n:"Kredibilitas Eksternal",d:"Gunakan nama tokoh, data riset, atau brand terkenal sebagai anchor.",ex:"Akhirnya Artist A bocorin suplemen diet yang selama ini dikonsumsi."},{n:"Hubungan ke Solusi",d:"Ciptakan keterkaitan dengan produk/solusi kamu.",ex:"Ternyata 80% kandungannya juga mirip dengan produk ini."}]},
  {id:30,name:"Proof - Benefit",funnel:"mof",desc:"Gunakan bukti nyata sebagai attention utama, lalu highlight manfaatnya.",tags:["Social Proof","Before After","Visual"],steps:[{n:"Proof",d:"Tunjukkan bukti visual atau data yang langsung menarik perhatian.",ex:"Before after penggunaan serum rambut bebas dari kerontokan."},{n:"Benefit",d:"Jelaskan manfaat nyata yang terlihat dari bukti tersebut.",ex:"Rambut jadi tambah kuat dan bagian rontok sudah tumbuh baru."}]},
  {id:31,name:"Problem - Statistik - Solution",funnel:"mof",desc:"Perkuat kepercayaan dengan data statistik sebelum menawarkan solusi.",tags:["Data","Trust","Credibility"],steps:[{n:"Problem",d:"Mulai dengan masalah yang dirasakan audience.",ex:"Pantes aja kucing kamu harus bolak-balik ke dokter."},{n:"Statistik",d:"Hadirkan data atau angka mengejutkan.",ex:"Menurut data, 60% kucing yang makan jenis A lebih rentan penyakit."},{n:"Solution",d:"Berikan solusi kamu sebagai jalan keluar.",ex:"Segera obati dengan beberapa jenis obat yang sudah terbukti."}]},
  {id:32,name:"Useful - Urgent - Unique",funnel:"bof",desc:"Nilai guna + urgensi + keunikan untuk mendorong keputusan pembelian.",tags:["Sales","FOMO","Conversion"],steps:[{n:"Useful",d:"Jelaskan nilai nyata yang akan didapatkan.",ex:"Webinar untuk bisnis UMKM menyehatkan keuangan."},{n:"Urgent",d:"Ciptakan urgensi nyata — limited slot, waktu terbatas.",ex:"Hanya untuk 10 slot saja."},{n:"Unique",d:"Sampaikan keunikan yang tidak bisa didapat di tempat lain.",ex:"Kamu bisa menanyakan semua pertanyaan tanpa terbatas durasi."}]},
  {id:33,name:"Stop - Listen",funnel:"bof",desc:"Ciptakan keraguan yang membuat audience mau mendengar sebelum membeli.",tags:["Pre-Sales","Curiosity","Conversion"],steps:[{n:"Stop",d:"Gunakan kata 'Jangan' untuk menghentikan audience.",ex:"Jangan beli sepatu luxury Balenciaga"},{n:"Listen",d:"Jelaskan syarat atau info yang harus diketahui sebelum membeli.",ex:"sebelum kamu memahami 4 hal ini yang menyelamatkan uang kamu."}]},
  {id:34,name:"Stop - Fear - Listen",funnel:"bof",desc:"Versi lebih kuat dari Stop-Listen dengan tambahan konsekuensi menakutkan.",tags:["Fear","Sales","Pre-Decision"],steps:[{n:"Stop",d:"Hentikan audience dengan larangan keras.",ex:"Jangan mulai bisnis"},{n:"Fear",d:"Tunjukkan konsekuensi fatal.",ex:"kalau kamu tidak ingin gagal di 3 bulan pertama"},{n:"Listen",d:"Pahami 3 aspek marketing ini untuk membangun bisnis baru.",ex:"Pahami 3 aspek marketing ini untuk membangun bisnis baru."}]},
  {id:35,name:"Promotion - Benefit - Urgency",funnel:"bof",desc:"Formula promosi dengan urgensi — ideal untuk flash sale.",tags:["Promotion","FOMO","Sales"],steps:[{n:"Promotion",d:"Sebutkan penawaran promosi dengan jelas dan menarik di awal.",ex:"50% Discount produk pengering rambut."},{n:"Benefit",d:"Jelaskan nilai yang didapat saat membeli dengan harga promo.",ex:"Kapan lagi bisa punya produknya dengan harga lebih murah?"},{n:"Urgency",d:"Ciptakan deadline atau batasan nyata.",ex:"Hanya tersedia untuk 10 pembeli pertama."}]},
  {id:36,name:"Why - Try - Buy",funnel:"bof",desc:"Formula persuasif: alasan → mencoba → membeli.",tags:["Persuasion","Sales","Psychology"],steps:[{n:"Why",d:"Berikan alasan kuat mengapa audience harus peduli.",ex:"Bahkan pasangan kamu ga akan bisa menciptakan kebahagiaan di diri kamu."},{n:"Try",d:"Persuasi ke value tanpa langsung menjual.",ex:"Coba berkaca kembali apa masalah masa lalu yang masih menghantui."},{n:"Buy",d:"Sebutkan di mana mereka bisa mendapatkan solusi kamu.",ex:"Kamu bisa gunakan app ini untuk konsultasi langsung dengan psikolog."}]},
  {id:37,name:"Happy Customer - Story - Action",funnel:"bof",desc:"Gunakan testimoni positif sebagai cerita yang menggerakkan calon pembeli.",tags:["Testimonial","Social Proof","Sales"],steps:[{n:"Happy Customer",d:"Perkenalkan customer yang bahagia secara unik.",ex:"Kaget dikirim kue sama Pak Andi, salah satu customer saya."},{n:"Story",d:"Ceritakan transformasi nyata yang dialami customer tersebut.",ex:"Katanya senang banget dengan terapi yang bisa bikin sembuh setelah 7 tahun."},{n:"Action",d:"Berikan satu CTA yang jelas dan langsung.",ex:"Kamu yang punya keluhan sama, juga bisa sembuh seperti Pak Andi."}]},
  {id:38,name:"Solution - Impact - Problem",funnel:"bof",desc:"Balik urutan klasik: solusi dulu, baru tunjukkan masalah yang terselesaikan.",tags:["Sales","Product First","Conversion"],steps:[{n:"Solution",d:"Langsung sebutkan solusi/produk tanpa basa-basi.",ex:"Inovasi baru sunscreen dengan SPF 50."},{n:"Impact",d:"Jelaskan dampak positif yang dirasakan pengguna.",ex:"Ga hanya menjaga kulit dari UV, tapi juga memutihkan."},{n:"Problem Solved",d:"Akhiri dengan masalah spesifik yang terselesaikan.",ex:"Solusi untuk kamu yang sering kusam karena sinar matahari."}]},
  {id:39,name:"Problem × Impact × Impact → Solution",funnel:"bof",desc:"Double impact — perkuat ketakutan dengan 2 lapisan konsekuensi.",tags:["Fear","Urgency","Conversion"],steps:[{n:"Problem",d:"Sebutkan masalah utama yang dialami.",ex:"Kebiasaan memencet jerawat ga hanya bikin kulit radang."},{n:"Impact 1",d:"Tunjukkan konsekuensi pertama yang langsung terasa.",ex:"Tapi juga menimbulkan jerawat yang semakin banyak."},{n:"Impact 2",d:"Tunjukkan konsekuensi kedua yang lebih parah.",ex:"Jadi sia-sia percuma mengeluarkan uang untuk acne serum."},{n:"Solution",d:"Hadirkan solusi sebagai jalan keluar.",ex:"Terapkan 3 hal ini untuk berhenti memencet jerawat."}]},
  {id:40,name:"Problem - Grouping - Solution",funnel:"bof",desc:"Tunjukkan siapa yang TIDAK cocok — paradox yang justru mengundang.",tags:["Psychology","Sales","Exclusivity"],steps:[{n:"Problem",d:"Sampaikan masalah yang ingin diselesaikan.",ex:"Cara instan menguasai bahasa Inggris dalam 30 hari."},{n:"Exclusion Group",d:"Sebutkan kelompok yang 'tidak akan cocok' — ini justru menarik yang lain.",ex:"Anak-anak fakultas sastra Inggris pasti ga akan menerima metode ini."},{n:"Solution",d:"Jelaskan pendekatan kamu yang berbeda dan terbukti.",ex:"Karena metode ini hasil otodidak saya untuk belajar dengan cara baru."}]},
  {id:41,name:"Before - After",funnel:"bof",desc:"Visualisasi perubahan sederhana dari kondisi buruk ke kondisi ideal.",tags:["Before After","Visual","Conversion"],steps:[{n:"Before",d:"Gambarkan kondisi sebelum dengan bahasa emosional.",ex:"Biasanya selalu insecure sama kulit kusam tiap tampil nyanyi."},{n:"After",d:"Gambarkan kondisi sesudah yang jauh lebih baik.",ex:"Tapi itu dulu sebelum akhirnya aku rajin perawatan di klinik ini."}]},
  {id:42,name:"Opposite Formula",funnel:"bof",desc:"Gunakan pesan berlawanan dari ekspektasi audience — shock dan keingintahuan.",tags:["Psychology","Viral","Shock"],steps:[{n:"Larangan Terbalik",d:"Buat kalimat larangan yang sebenarnya mengarah ke hal positif.",ex:"Jangan minum merek minuman ini"},{n:"Alasan Berlawanan",d:"Berikan alasan yang bertentangan dengan ekspektasi.",ex:"karena usus dan pencernaan kamu akan menjadi lebih sehat."}]},
  {id:43,name:"You Failed Formula",funnel:"bof",desc:"Psikologi takut gagal — orang lebih takut rugi daripada tidak dapat untung.",tags:["Psychology","Fear","Conversion"],steps:[{n:"Larangan Ironis",d:"Buat kalimat melarang sesuatu yang tidak diinginkan siapapun.",ex:"Jangan gunakan shampoo ini"},{n:"Konsekuensi",d:"Sebutkan konsekuensi buruk jika TIDAK menggunakan produk kamu.",ex:"biar rambut kamu terus berketombe seumur hidup."}]},
  {id:44,name:"Excitement - Problem - Solution",funnel:"bof",desc:"Mulai dengan emosi positif/excited sebelum masuk ke masalah dan solusi.",tags:["Emotional","Sales","Positive Hook"],steps:[{n:"Excitement",d:"Buka dengan konteks yang membuat audience excited.",ex:"Akhirnya terjawab juga setelah 7 hari pencarian saya."},{n:"Problem Reveal",d:"Ungkap masalah yang akhirnya ditemukan jawabannya.",ex:"Kenapa hire KOL besar belum pasti memberikan keuntungan."},{n:"Solution",d:"Berikan solusi yang langsung bisa diterapkan.",ex:"Kamu tinggal dengar dan langsung terapin. Ga perlu trial error."}]},
  {id:45,name:"Problem - Solution - Anchor",funnel:"bof",desc:"Gunakan 'anchor' di akhir untuk memastikan audience menonton hingga selesai.",tags:["Retention","Sales","Anchor"],steps:[{n:"Problem",d:"Buka dengan masalah yang langsung relevan.",ex:"Ini penyebab CV kamu terlihat kurang menarik di mata HR."},{n:"Solution",d:"Berikan solusi yang mengundang untuk terus menonton.",ex:"Utamakan meletakkan prestasi di bagian teratas CV."},{n:"Anchor",d:"Tambahkan jangkar di menit akhir — konten paling berharga.",ex:"Di menit akhir saya akan praktikkan cara penulisan yang benar."}]},
  {id:46,name:"Number - Must",funnel:"bof",desc:"Angka + kata wajib menciptakan konten esensial yang tidak bisa dilewatkan.",tags:["List","Urgency","Education"],steps:[{n:"Angka",d:"Sebutkan angka spesifik yang menandai jumlah item penting.",ex:"4 merek roti"},{n:"Must/Wajib",d:"Gunakan 'wajib kamu ketahui' untuk menciptakan urgensi.",ex:"yang wajib kamu ketahui untuk membuat burger yang sempurna."}]},
  {id:47,name:"Solution × Solution × Solution",funnel:"bof",desc:"Triple solution — tunjukkan produk bisa menyelesaikan banyak masalah sekaligus.",tags:["Product","Value","Versatile"],steps:[{n:"Solution 1",d:"Sebutkan keunggulan utama produk.",ex:"Bantal dari kapas premium yang sangat empuk."},{n:"Solution 2",d:"Tunjukkan masalah lain yang juga terselesaikan.",ex:"Bisa meningkatkan kualitas tidur secara signifikan."},{n:"Solution 3",d:"Tambahkan benefit ketiga yang tidak terduga.",ex:"Dan juga menghindari cedera leher saat tidur."}]},
  {id:48,name:"Features - Advantage - Analogy",funnel:"bof",desc:"Kemas harga dengan analogi agar audience lebih percaya diri untuk membeli.",tags:["Pricing","Psychology","Sales"],steps:[{n:"Features",d:"Tonjolkan fitur utama yang paling menarik.",ex:"Kopi robusta pekat dari hasil biji berkualitas."},{n:"Advantage",d:"Jelaskan keunggulan utama yang membuat produk berbeda.",ex:"Bikin cara ngopi kamu jadi lebih hemat."},{n:"Analogy Harga",d:"Kemas harga dengan analogi yang membuat audience merasa worth it.",ex:"Dengan kopi ini sama aja kamu menghemat 1 bungkus kopi per minggu."}]},
  {id:49,name:"Flash Promo Formula",funnel:"bof",desc:"Flash sale yang agresif dan time-bound untuk mendorong keputusan cepat.",tags:["Flash Sale","FOMO","Limited"],steps:[{n:"Flash Offer",d:"Buka langsung dengan penawaran menggiurkan dan time-limited.",ex:"Hari ini saja! Diskon 70% untuk semua kelas online."},{n:"Value Stack",d:"Tumpuk nilai yang didapat — buat pembeli merasa sangat beruntung.",ex:"Senilai 2 juta, kamu cukup bayar 600 ribu dan langsung akses seumur hidup."},{n:"Countdown",d:"Ciptakan hitungan mundur atau batas yang membuat tidak mau menunggu.",ex:"Tinggal 5 slot tersisa — setelah itu harga kembali normal."}]},
  {id:50,name:"Promotion - Benefit - Urgency (Flash)",funnel:"bof",desc:"Versi flash yang lebih spesifik dengan target audiens dan benefit stacking.",tags:["Flash","Conversion","Stack"],steps:[{n:"Promo Flash",d:"Sebutkan angka diskon yang mengejutkan di kalimat pertama.",ex:"50% OFF sampai malam ini saja."},{n:"Benefit Stack",d:"Daftarkan 3+ manfaat yang didapat sekaligus dari satu pembelian.",ex:"Dapat e-book, akses komunitas, dan 1 sesi konsultasi GRATIS."},{n:"Urgency Hard",d:"Buat urgensi yang tidak bisa ditawar — stok, waktu, atau akses terbatas.",ex:"Hanya 7 slot tersisa dan tidak akan dibuka lagi bulan ini."}]},
];

export const HOOK_TYPES: HookType[] = [
  {id:'shock',label:'Shock & Surprise',name:'Fakta Mengejutkan',formula:'[Fakta/angka tak disangka] + [konteks mengejutkan]',ex:'"Saya kehilangan 5 juta dalam 3 hari karena 1 kesalahan ini"',strength:92},
  {id:'question',label:'Curiosity Hook',name:'Pertanyaan Menggantung',formula:'[Pertanyaan retorik] + [hint jawaban tak terduga]',ex:'"Kenapa kreator dengan 100rb followers bisa kalah sama akun baru?"',strength:88},
  {id:'jangan',label:'Pattern Interrupt',name:'Jangan / Stop',formula:'"Jangan [lakukan X] sebelum kamu [tahu ini]"',ex:'"Jangan upload konten sebelum kamu tonton video ini dulu"',strength:90},
  {id:'story',label:'Story Hook',name:'Pembuka Cerita',formula:'"[Situasi tak terduga] yang akhirnya mengubah segalanya"',ex:'"Hari ini saya ketemu orang yang dulu paling saya benci"',strength:85},
  {id:'pain',label:'Pain Hook',name:'Pain Point Langsung',formula:'"[Masalah spesifik]? Kamu tidak sendiri — ini yang terjadi"',ex:'"Udah posting 30 hari tapi views segitu-segitu aja?"',strength:87},
  {id:'number',label:'Number Hook',name:'Angka Spesifik',formula:'"[Angka] [hal] yang [hasil mengejutkan]"',ex:'"7 kata yang bisa 10x lipat penjualan kamu hari ini"',strength:84},
  {id:'contrast',label:'Contrast Hook',name:'Kontras / Before-After',formula:'"Dulu [kondisi buruk] — sekarang [kondisi baik]. Ini yang berubah"',ex:'"Dulu 0 penjualan sebulan — sekarang 300 order per hari"',strength:86},
  {id:'secret',label:'Exclusive Hook',name:'Rahasia / Bocoran',formula:'"Baru berani bongkar [rahasia/info eksklusif]"',ex:'"Baru berani bongkar cara saya bisa viral tanpa spend ads"',strength:89},
];

export const HT_DATA: HashtagsDataset = {
  mega:[{tag:'#fyp',vol:'500B+',added:false},{tag:'#viral',vol:'200B+',added:false},{tag:'#tiktok',vol:'100B+',added:false},{tag:'#foryou',vol:'150B+',added:false},{tag:'#foryoupage',vol:'80B+',added:false}],
  big:[{tag:'#konten',vol:'5B+',added:false},{tag:'#contentcreator',vol:'20B+',added:false},{tag:'#bisnis',vol:'3B+',added:false},{tag:'#marketing',vol:'8B+',added:false},{tag:'#digitalmarketing',vol:'4B+',added:false},{tag:'#umkm',vol:'2B+',added:false},{tag:'#entrepreneur',vol:'15B+',added:false},{tag:'#jualan',vol:'1B+',added:false}],
  medium:[{tag:'#tipskonten',vol:'500M+',added:false},{tag:'#strategi',vol:'300M+',added:false},{tag:'#brandingpersonal',vol:'200M+',added:false},{tag:'#copywriting',vol:'400M+',added:false},{tag:'#tipsmarketing',vol:'600M+',added:false},{tag:'#contentstrategy',vol:'250M+',added:false},{tag:'#jualanOnline',vol:'800M+',added:false},{tag:'#tipsbisnis',vol:'700M+',added:false}],
  niche:[{tag:'#jagongebrand',vol:'10M+',added:false},{tag:'#kontenedukasi',vol:'50M+',added:false},{tag:'#tipscreator',vol:'80M+',added:false},{tag:'#hookkonten',vol:'5M+',added:false},{tag:'#viralhook',vol:'20M+',added:false},{tag:'#scriptkonten',vol:'8M+',added:false},{tag:'#organikreach',vol:'15M+',added:false}]
};
